name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Access file system
      uses: actions/checkout@v3

    - name: Build go from tip
      uses: iwdgo/gotip-build
      id: gotip
      with:
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      with:
        name: gotip-${{ runner.os }}-${{ runner.arch }}
        path: .\go\bin
