name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Access file system
      uses: actions/checkout@v3

    - name: Cherry pick patches from Gerrit
      run: |
        # https://go.dev/issue/7535
        https://go-review.googlesource.com/c/go/+/107755#:~:text=5b567c4.diff.base64-,5b567c4.diff.zip,-CLOSE

    - name: Build go from tip
      uses: iwdgo/gotip-build@master-windows
      id: gotip
      with:
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      with:
        name: gotip-${{ runner.os }}-${{ runner.arch }}
        path: .\go\bin
