name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
      id: go

    - name: Access file system
      uses: actions/checkout@v3

    - name: Format patches
      run: | # 4 of 6. TODO Investigate conflicts during git am
        # go.dev/issue/7535
        git fetch https://go.googlesource.com/go refs/changes/55/107755/9 && git checkout -b change-107755 FETCH_HEAD && git format-patch -1
        # go.dev/issue/8068
        git fetch https://go.googlesource.com/go refs/changes/75/596975/1 && git checkout -b change-596975 FETCH_HEAD && git format-patch -1
        # go.dev/issue/9519
        # git fetch https://go.googlesource.com/go refs/changes/56/116056/3 && git checkout -b change-116056 FETCH_HEAD && git format-patch -1
        # go.dev/issue/10538
        git fetch https://go.googlesource.com/go refs/changes/16/108616/6 && git checkout -b change-108616 FETCH_HEAD && git format-patch -1
        # go.dev/issue/13185
        git fetch https://go.googlesource.com/go refs/changes/97/108797/6 && git checkout -b change-108797 FETCH_HEAD && git format-patch -1
        # go.dev/issue/20614
        # git fetch https://go.googlesource.com/go refs/changes/55/104655/6 && git checkout -b change-104655 FETCH_HEAD && git format-patch -1

    - name: Build go from tip
      uses: iwdgo/gotip-build@master-windows
      id: gotip
      with:
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      with:
        name: gotip-${{ runner.os }}-${{ runner.arch }}
        path: .\go\bin
